# Generated by Django 4.0.3 on 2022-04-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(to='crm.article'),
        ),
    ]
